### ISSUE TITLE
trigger_once is breaking certain campaign maps

### ISSUE THREAD

**Issue by ChapperNi** [ZehMatt/Lambda#325] opened 2024-11-03 05:09 UTC
the trigger_once entity is causing some maps trigger_teleport to not function, i used Icarus Project 1&2's starting teleporter as an example. deleting trigger_once.lua in the entities folder makes them work again

**Comment by ZehMatt** [comment] 2024-11-03 17:04
I will have a look. Also are you using the workshop version or the code from GitHub?

**Comment by ZehMatt** [comment] 2024-11-03 17:36
I found the root cause but I'm not even sure why that's a thing.
![image](https://github.com/user-attachments/assets/972622e9-8a1d-4f47-87a5-d10979231f77)
this should be
![image](https://github.com/user-attachments/assets/fdbabf00-6b74-49fe-aa11-a29b2af250c8)
I will push a work-around for this, there is absolutely nothing in the Source SDK that deals with those 🤷‍♂️ 

Edit: Looks like newer Source games use this according to Rubat.

**Comment by ZehMatt** [comment] 2024-11-03 18:12
This should be fixed, let me know if you run into any other issues.

**Closed as completed** 2024-11-03 18:11 UTC
