### ISSUE TITLE
d1_canals_08 Apache being kill-able

### ISSUE THREAD

**Issue by Mikk155** [ZehMatt/Lambda#340] opened 2024-12-21 00:20 UTC
One of the players did shut down the apache by using the mounted guns
![20241220173709_1](https://github.com/user-attachments/assets/5eafeede-223b-4573-907f-150c63febeb7)

**Comment by ZehMatt** [comment] 2024-12-21 12:46
I'm not sure if that is a bug, I think that is also possible in Half-Life 2

**Comment by Mikk155** [comment] 2024-12-21 14:05
I don't think so since that apache is supposed to follow us during the rest of the level, and think it would be the same apache as the next level, argumentaly speaking.

**Comment by ZehMatt** [comment] 2024-12-21 15:45
In Half-Life 2 if you only go as far until the helicopter spawns you can avoid the gate closing and you can totally go back to mount the turret and get rid of the chopper. Closing this as its not a bug.

**Closed as completed by ZehMatt** 2024-12-21 15:45 UTC

**Comment by Mikk155** [comment] 2024-12-21 17:16
I may have been made a mistake explaining too, i havent ever killed that apache in the original game.

Is not that the fact the apache can be killed but seems that the apache never did get the "go away" sequence that is supposed to do, so we just killed it.
