### ISSUE TITLE
Chapter 1 (Trainstation) bug

### ISSUE THREAD

**Issue by Sp-Lily** [ZehMatt/Lambda#121] opened 2018-11-13 19:16 UTC
In said chapter:
* Citizens missing their pre-defined dialog when try to interact with them (Not talking) also they already recognized the player as Gordon Freeman. 
* Some citizen also not executing their scripted sequence, for example "Waiting in line to get food" sequence

**Comment by ZehMatt** [comment] 2018-11-13 21:57
Thanks for the report. I'm aware of those bugs however I wasn't able to pinpoint yet why they do that. However the only game breaking thing are those in the queue which "sometimes" don't move forward if they get interrupted by whatever.

**Comment by Sp-Lily** [comment] 2018-11-14 09:46
Console log can help perhaps

**Comment by ZehMatt** [comment] 2018-11-14 15:07
I think the issue is somewhere hidden in the player code as Garry's Mod implements its own player class and it might have something to do with that and how AI is treated in multiplayer.

**Comment by ZehMatt** [comment] 2018-11-14 18:07
Well I found the root cause for this, Garry's Mod has a slightly different scripts/talker/npc_citizen.txt script where the criteria "IsGordonCriminal" was removed.

**Comment by Sp-Lily** [comment] 2018-11-14 21:19
Oh, can you add them? I mean pack it together after do slight modification to the file?

**Comment by ZehMatt** [comment] 2018-11-14 22:52
I can not, apparently Willox made sure scripts can not be overridden. However he promised to look into this specific case.

**Comment by Sp-Lily** [comment] 2018-11-15 08:39
Ah great. Oh I forget to tell another bug. Did you notice that in the Interrogation Room where Barney show to Doctor Kleiner that Gordon Freeman come, Barney go inside the small storage room with the player and the door isn't close after Barney tell Player to escape?

**Comment by ZehMatt** [comment] 2018-11-15 12:30
Yea its left open on purpose so players wont be locked out.

**Comment by Sp-Lily** [comment] 2018-11-16 12:28
I understand now. How about the Intro of Chapter 1? Pods movement in citadel kinda weird

**Comment by ZehMatt** [comment] 2018-11-16 19:49
I've already implemented point_viewcontrol and yea I noticed pods being wonky but I think thats a Garry's Mod thing lately.

**Comment by Sp-Lily** [comment] 2018-11-16 20:47
So impossible to fix for the Pods?

**Comment by ZehMatt** [comment] 2018-11-16 22:09
The pods are fixed. I just published it to the workshop.

**Comment by Sp-Lily** [comment] 2018-11-17 13:14
Awesome :D

**Comment by Sp-Lily** [comment] 2018-11-19 03:48
I think I know what's the cause of those citizen missing their pre-defined dialogue, also the game not run the scripted sequence properly. I got this kind of message generated on console:

`CSceneEntity lcs_sewercops_converse unable to find actor named "!target1"`
`CSceneEntity lcs_sewercops_converse unable to find actor named "!target2"`
`CSceneEntity lcs_sewercops_startle unable to find actor named "!target1"`
`CSceneEntity lcs_sewercops_startle unable to find actor named "!target2"`

This is the example where 2 Metro-Police doing conversation (sequence isn't executed) while I'm below them in map d1_canals_01a. Another example is Mark (Citizen with Vort inside the red trailer) isn't saying "Becareful" to Gordon after opening the trailer door, same console message generated as above but with different target name.

**Comment by ZehMatt** [comment] 2018-11-19 06:04
I was able to fix the part in d1_canals_01a that was due to the NPC's literally missing. The one "mark_boxcar_human_opendoor" is same as in Half-Life 2, its just a missing "move to" script, nothing game breaking. Also I would appreciate if you could open new issues in the future to better track them.

**Comment by Sp-Lily** [comment] 2018-11-19 08:17
Alright, I'll do it by moving my comment above to the new issue

**Comment by ZehMatt** [comment] 2018-11-22 10:27
NPC's should no longer greet you as long you aren't criminal, thanks Willox.

**Comment by ZehMatt** [comment] 2019-02-07 22:53
Most cases should be fixed in the latest develop version.

**Closed as completed by ZehMatt** 2019-02-07 22:53 UTC
