### ISSUE TITLE
Missing Scripted Sequence

### ISSUE THREAD

**Issue by Sp-Lily** [ZehMatt/Lambda#128] opened 2018-11-19 13:40 UTC
List of found maps that are having missing/unknown scripted sequence:
- [x] **d1_eli_01**
_Alyx missing her Scripted Sequence making her T-Posing. `Details of the Sequence are in the console.`_

- [x] **d1_eli_02**
_Alyx and Dog also missing their Scripted Sequences. Alyx T-Pose when trying to sit at the side of the Scrapyard `Details of the Sequence are in the console.`_

**Comment by ZehMatt** [comment] 2018-11-19 16:54
I have a couple question for that. 
- Are you playing listen server or dedicated server? 
- Do you have Half-Life 2 mounted on server and client?
- Can you reproduce this issue in Half-Life 2?

**Comment by Sp-Lily** [comment] 2018-11-19 21:46
1. I'm playing on Listen Server
2. Yes it's mounted
3. I can't reproduce this Issue in Half-Life 2, everything is normal

**Comment by Balimbanana** [comment] 2018-11-20 05:12
Ep2 models don't have the sequences required for these, if you are subscribed to this, it will break them for HL2: Half-Life 2 Campaign Content https://steamcommunity.com/sharedfiles/filedetails/?id=129361322

I just tested, subscribed, started map, T-Pose.

Unsubscribe, start map, correct sequences.

This is something to keep in mind though for Ep1/2 support in Lambda, the sequences will break depending on what version of the models are active. I wonder if it would be possible to check what game type or mod is active and set their models accordingly. This would require duplicating the models and using different names such as `models/alyxep2.mdl` `models/alyxep1.mdl` with their corresponding vtx's, phy and such.

The other option would be attempting to load the model directly from the vpk that is in the active game type/mod.

This also applies to the vort on `d1_canals_13` from #127

**Comment by Sp-Lily** [comment] 2018-11-21 00:59
Ah you're right, I have addon similar with the one you post here, I uninstall it and both issues gone including #127. But i'm still make sure everything working correctly by keep doing bug hunting

**EDIT: I found new missing gesture and update my comment in #127**

**Comment by knoxed** [comment] 2024-07-27 15:45
Closing this since I did not find any animation issues on these 2 maps.

**Closed as completed by knoxed** 2024-07-27 15:45 UTC
